export class Speakers {
  public static names: Record<string, string> = {
    'Front Left': 'FL',
    'Front Right': 'FR',
    'Center': 'C',
    'Subwoofer 1': 'SW',
    'Subwoofer 2': 'SW2',
    'Surround Left': 'SL',
    'Surround Right': 'SR',
    'Surround Back Left': 'SBL',
    'Surround Back Right': 'SBR',
    'Surround Back': 'SB',
    'Front Height Left': 'FHL',
    'Front Height Right': 'FHR',
    'Front Wide Left': 'FWL',
    'Front Wide Right': 'FWR',
    'Top Front Left': 'TFL',
    'Top Front Right': 'TFR',
    'Top Middle Left': 'TML',
    'Top Middle Right': 'TMR',
    'Top Rear Left': 'TRL',
    'Top Rear Right': 'TRR',
    'Rear Height Left': 'RHL',
    'Rear Height Right': 'RHR',
    'Front Dolby Left': 'FDL',
    'Front Dolby Right': 'FDR',
    'Surround Dolby Left': 'SDL',
    'Surround Dolby Right': 'SDR',
    'Back Dolby Left': 'BDL',
    'Back Dolby Right': 'BDR',
    'Surround Height Left': 'SHL',
    'Surround Height Right': 'SHR',
    'Top Surround': 'TS',
  }

  public static codes: Record<string, string> = {
    'FL': 'Front Left',
    'FR': 'Front Right',
    'C': 'Center',
    'SW': 'Subwoofer 1',
    'SW2': 'Subwoofer 2',
    'SL': 'Surround Left',
    'SR': 'Surround Right',
    'SBL': 'Surround Back Left',
    'SBR': 'Surround Back Right',
    'SB': 'Surround Back',
    'FHL': 'Front Height Left',
    'FHR': 'Front Height Right',
    'FWL': 'Front Wide Left',
    'FWR': 'Front Wide Right',
    'TFL': 'Top Front Left',
    'TFR': 'Top Front Right',
    'TML': 'Top Middle Left',
    'TMR': 'Top Middle Right',
    'TRL': 'Top Rear Left',
    'TRR': 'Top Rear Right',
    'RHL': 'Rear Height Left',
    'RHR': 'Rear Height Right',
    'FDL': 'Front Dolby Left',
    'FDR': 'Front Dolby Right',
    'SDL': 'Surround Dolby Left',
    'SDR': 'Surround Dolby Right',
    'BDL': 'Back Dolby Left',
    'BDR': 'Back Dolby Right',
    'SHL': 'Surround Height Left',
    'SHR': 'Surround Height Right',
    'TS': 'Top Surround',
  }
}